homepage:
  name: Homepage
  description: The page that will be displayed when your Embassy Pages .onion address is visited. Since this page is technically publicly accessible, you can choose to which type of page to display.
  type: union
  default: welcome
  tag:
    id: type
    name: Type
    variantNames:
      welcome: Welcome Page
      index: Index of Subdomains
      filebrowser: File Browser Directory
      redirect: Redirect
      fuck-off: Fuck Off
  variants:
    welcome: {}
    index: {}
    filebrowser:
      subdomain:
        type: string
        name: Subdomain
        description: The subdomain of your Embassy Pages .onion address to host the website on. For example, a value of "me" would produce a website hosted at http://me.myaddress.onion.
        pattern: '^[a-z-]+$'
        patternDescription: May contain only lowercase characters and hyphens.
        nullable: false
      directory:
        type: string
        name: Directory
        description: The directory in File Browser that contains the static files of your website. For example, a value of "websites/resume_site" would tell Embassy Pages to look for that directory in File Browser.
        pattern: '^(\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\.*)+)(\/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|\/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\.*)+)*\/?$'
        patternDescription: Must be a valid relative file path
        nullable: false
    redirect:
      target:
        type: string
        name: Target Subdomain
        description: The subdomain of your Embassy Pages .onion address to redirect to. This should be the name of another subdomain on Embassy Pages.
        pattern: '^[a-z-]+$'
        patternDescription: May contain only lowercase characters and hyphens.
        nullable: false
    fuck-off: {}
subdomains:
  type: list
  subtype: union
  name: Subdomains
  description: The websites you want to serve
  default: []
  range: '[0, *)'
  spec:
    type: union
    displayAs: '{{subdomain}}'
    uniqueBy: subdomain
    default: filebrowser
    tag:
      id: type
      name: Type
      variantNames:
        filebrowser: File Browser Directory
        redirect: Redirect
        fuck-off: Fuck Off
    variants:
      filebrowser:
        subdomain:
          type: string
          name: Subdomain
          description: The subdomain of your Embassy Pages .onion address to host the website on. For example, a value of "me" would produce a website hosted at http://me.myaddress.onion.
          pattern: '^[a-z-]+$'
          patternDescription: May contain only lowercase characters and hyphens.
          nullable: false
        directory:
          type: string
          name: Directory
          description: The directory in File Browser that contains the static files of your website. For example, a value of "websites/resume_site" would tell Embassy Pages to look for that directory in File Browser.
          pattern: '^(\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\.*)+)(\/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|\/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\.*)+)*\/?$'
          patternDescription: Must be a valid relative file path
          nullable: false
      redirect:
        subdomain:
          type: string
          name: Source Subdomain
          description: The subdomain of your Embassy Pages .onion address to redirect from.
          pattern: '^[a-z-]+$'
          patternDescription: May contain only lowercase characters and hyphens.
          nullable: false
        target:
          type: string
          name: Target Subdomain
          description: The subdomain of your Embassy Pages .onion address to redirect to. This should be the name of another subdomain on Embassy Pages. Leave empty to redirect to the homepage.
          pattern: '^[a-z-]+$'
          patternDescription: May contain only lowercase characters and hyphens.
          nullable: true
      fuck-off: {}