homepage:
  name: Homepage
  description: The page that will be displayed when your Embassy Pages .onion address is visited. Since this page is technically publicly accessible, you can choose to which type of page to display.
  type: union
  default: welcome
  tag:
    id: type
    name: Type
    variant-names:
      welcome: Welcome
      index: Subdomain Index
      filebrowser: Web Page
      redirect: Redirect
      fuck-off: Fuck Off
  variants:
    welcome: {}
    index: {}
    filebrowser:
      directory:
        type: string
        name: Directory Path
        description: The path to the directory in File Browser that contains the static files of your website. For example, a value of "websites/resume_site" would tell Embassy Pages to look for that directory in File Browser.
        pattern: "^(\\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)(/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)*/?$"
        pattern-description: Must be a valid relative file path
        nullable: false
    redirect:
      target:
        type: string
        name: Target Subdomain
        description: The name of the subdomain to redirect users to. This must be a valid subdomain site within your Embassy Pages. 
        pattern: '^[a-z-]+$'
        pattern-description: May contain only lowercase characters and hyphens.
        nullable: false
    fuck-off: {}
subdomains:
  type: list
  name: Subdomains
  description: The websites you want to serve.
  default: []
  range: '[0, *)'
  subtype: object
  spec:
    unique-by: name
    display-as: "{{name}}"
    spec:
      name:
        type: string
        nullable: false
        name: Subdomain name
        description: The subdomain of your Embassy Pages .onion address to host the website on. For example, a value of "me" would produce a website hosted at http://me.myaddress.onion.
        pattern: "^[a-z-]+$"
        pattern-description: "May contain only lowercase characters and hyphens"
      settings:
        type: union
        name: Settings
        description: The desired behavior you want to occur when the subdomain is visited. You can either redirect to another subdomain, or load a web page from File Browser.
        default: filebrowser
        tag:
          id: type
          name: Type
          variant-names:
            filebrowser: Web Page
            redirect: Redirect
        variants:
          filebrowser:
            directory:
              type: string
              name: Directory Path
              description: The path to the directory in File Browser that contains the static files of your website. For example, a value of "websites/resume_site" would tell Embassy Pages to look for that directory in File Browser.
              pattern: "^(\\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)(/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)*/?$"
              pattern-description: Must be a valid relative file path
              nullable: false
          redirect:
            target:
              type: string
              name: Target Subdomain
              description: The subdomain of your Embassy Pages .onion address to redirect to. This should be the name of another subdomain on Embassy Pages. Leave empty to redirect to the homepage.
              pattern: '^[a-z-]+$'
              pattern-description: May contain only lowercase characters and hyphens.
              nullable: false